kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: chaos-mesh
  name: chaos-mesh-manager

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-chaos-mesh-manager
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["chaos-mesh.org"]
  resources: [ "*" ]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-chaos-mesh-manager
subjects:
- kind: ServiceAccount
  name: chaos-mesh-manager
  namespace: chaos-mesh
roleRef:
  kind: ClusterRole
  name: role-chaos-mesh-manager
  apiGroup: rbac.authorization.k8s.io
